stages:
  - test
  - name: deploy
    if: tag IS present

jobs:
  include:
    - stage: test
      language: node_js
      node_js:
        - "6"
      cache:
        directories:
          - "web/node_modules"
          - "web/.awcache"
      before_install:
        - cd web
      script:
        - npm run build

    - stage: test
      language: java
      cache:
        directories:
          - "$HOME/.m2"
      services:
        - postgresql
      addons:
        postgresql: "9.4"
      before_script:
        - cd server
        - psql -c 'create database cryptex;' -U postgres

    - stage: deploy
      sudo: required
      language: java
      node_js:
        - "6"
      cache:
        directories:
          - "$HOME/.m2"
          - "web/node_modules"
          - "web/.awcache"
      before_script:
        - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
        - heroku plugins:install heroku-cli-deploy
      script: skip
      before_deploy:
        - cd server # Clean up Server
        - mvn clean

        - cd ../web # Build Web Project
        - nvm install "6.11.4"
        - npm install
        - npm run build

        - cd ../server # Copy Web into Server for building
        - mkdir -p target/classes/static
        - mv ../web/bin/* target/classes/static/

        - mvn install -DskipTests=true -Dmaven.javadoc.skip=true # Build Server

        - cd .. # Move built Server jar to root
        - mv server/target/cryptex.jar .

        - heroku buildpacks:clear --app mitchtalmadge-cryptex
        - heroku buildpacks:set heroku/jvm --app mitchtalmadge-cryptex
      deploy:
        skip_cleanup: true
        provider: script
        script:
          - heroku deploy:jar cryptex.jar --app mitchtalmadge-cryptex
        on:
          tags: true