import {Injectable} from '@angular/core';
import {ApiService} from "./api/api.service";
import {ApiResponse} from "./api/api-response.model";

@Injectable()
export class SignInService {

    constructor(private apiService: ApiService) {
    }

    /**
     * Retrieves the Discord OAuth2 authorization URL as generated by the server.
     * @returns {Promise<ApiResponse>} The generated url.
     */
    public getDiscordAuthorizationUrl(): Promise<ApiResponse> {
        return this.apiService.get("/oauth/discord/authorize");
    }

}