import {Injectable} from '@angular/core';
import {ApiService} from "./api/api.service";
import {Observable} from "rxjs/Observable";
import {ApiResponse} from "./api/api-response.model";
import {HttpEvent} from "@angular/common/http";

@Injectable()
export class SignInService {

    constructor(private apiService: ApiService) {
    }

    /**
     * Retrieves the Discord OAuth2 query URL as generated by the server.
     * @returns {Promise<ApiResponse>} The generated url.
     */
    public getDiscordQueryUrl(): Promise<ApiResponse> {
        return this.apiService.get("/oauth/discord/query");
    }

}